### ISSUE TITLE
Need a calendar feed

### ISSUE THREAD

**Issue by suryanaga** [nwspk/nwspk-events#1]
**Use case:** I want to be able to view events I might go to at Newspeak in my calendar app. I personally use Sunrise because it pulls in both my Facebook events and Google events, but as long as the feed is either Google or .ical, I think many people would find it useful.

**Potential implementation:** A Zapier zap which creates a new event in a new Google Calendar everytime a new row is added on the "canonical" spreadsheet that Newspeak staff use.

**Comment by sirodoht** [comment]
I think this exists for a while now: webcal://newspeak.house/api/events.ics
